//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examples_ASPNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Bonuses = new HashSet<Bonus>();
        }
    
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual ICollection<Bonus> Bonuses { get; set; }
        public virtual Department Departments { get; set; }
    }
}
